services:
  food-box:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - CLOVA_URL=${CLOVA_URL}
      - CLOVA_SECRET_KEY=${CLOVA_SECRET_KEY}
