spring:
  application:
    name: foodbox

crawl:
  crawl-url: https://foodboxofficial.modoo.at/?link=e3pla1lv
  css-selector: .gallery_img img
  image-index: 1

slack:
  slack-token: ${SLACK_TOKEN:"YOUR_SLACK_TOKEN_HERE"}
  slack-channel: ${SLACK_CHANNEL:"YOUR_SLACK_CHANNEL_HERE"}
  user-name: "점심봇"
  slack-url: "https://hooks.slack.com/services"

clova:
  url: ${CLOVA_URL:"YOUR_CLOVA_URL_HERE"}
  secret-key: ${CLOVA_SECRET_KEY:"YOUR_CLOVA_SECRET_KEY_HERE"}

server:
  port: 80
